debug: true

server:
  port: 8085

jwt:
  realm: NavPool HQ
  secret: ThisIsNotASecret
  identityKey: id

db:
  dialect: postgres
  host: localhost
  port: 8432
  username: navpool
  password: navpool
  dbname: navpool
  sslMode: disable
  logMode: true

explorer:
  url: https://api.v2.navexplorer.com

pool:
  url: http://localhost:8082

sentry:
  active: false